[package]
name = "actixtest"
version = "0.1.0"
authors = ["Anderson <andersonfrfilho@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-rt = "1.0"
derive_more = "0.99.11"
dotenv = "0.15.0"